services:
  nats:
    image: nats:2.10.18-alpine
    command: ['nats-server', '-js', '-sd', '/var/data']
    hostname: nats
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - 4222:4222
      - 8222:8222
      - 9222:9222
    volumes:
      - nats-data:/var/data/jetstream
    networks:
      - nats-network
    restart: always

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  nats-data:
  postgres_data:

networks:
  nats-network:
